# Generated by Django 6.0.3 on 2026-03-21 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_club_manager_profile_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
